### ISSUE TITLE
Mutliple forms not working correctly

### ISSUE THREAD

**Issue by lswamy** [dmetri333/FormValidation#1]
When there are multiple forms on the page, any form that gets submitted will try to validate the last form on the page.

I have attached two different tests. One that selects all forms in the selector and the other that selected each individual form.

[test.tar.gz](https://github.com/dmetri333/FormValidation/files/190245/test.tar.gz)

**Comment by dmetri333** [comment]
This has been addressed in the v1.1 release. Which is no available.
